---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/applications":
    post:
      summary: create application
      tags:
      - applications
      parameters: []
      responses:
        '201':
          description: appliction created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      application:
                        type: object
                        properties:
                          token:
                            type: string
                          name:
                            type: string
                          chats_number:
                            type: integer
                          created_at:
                            type: string
                          updated_at:
                            type: string
                required:
                - status
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 5
                  maxLength: 20
              required:
              - name
  "/v1/applications/{token}":
    parameters:
    - name: token
      in: path
      description: application token
      required: true
      schema:
        type: string
    get:
      summary: get application
      tags:
      - applications
      responses:
        '200':
          description: appliction found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      application:
                        type: object
                        properties:
                          token:
                            type: string
                          name:
                            type: string
                          chats_number:
                            type: integer
                          created_at:
                            type: string
                          updated_at:
                            type: string
                          chats:
                            type: array
                            items:
                              type: object
                              properties:
                                number:
                                  type: integer
                                messages_number:
                                  type: integer
                                created_at:
                                  type: string
                                updated_at:
                                  type: string
                required:
                - status
                - message
        '404':
          description: application not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                required:
                - status
                - message
    put:
      summary: update application
      tags:
      - applications
      parameters: []
      responses:
        '200':
          description: appliction updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      application:
                        type: object
                        properties:
                          token:
                            type: string
                          name:
                            type: string
                          chats_number:
                            type: integer
                          created_at:
                            type: string
                          updated_at:
                            type: string
                required:
                - status
                - message
        '400':
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                required:
                - status
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 5
                  maxLength: 20
              required:
              - name
  "/v1/applications/{application_token}/chats":
    parameters:
    - name: application_token
      in: path
      description: application token
      required: true
      schema:
        type: string
    post:
      summary: create chat
      tags:
      - chats
      responses:
        '201':
          description: chat created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      chat:
                        type: object
                        properties:
                          token:
                            type: string
                          number:
                            type: integer
                          messages_number:
                            type: integer
                          created_at:
                            type: string
                          updated_at:
                            type: string
                required:
                - status
                - message
  "/v1/applications/{application_token}/chats/{number}":
    parameters:
    - name: application_token
      in: path
      description: application token
      required: true
      schema:
        type: string
    - name: number
      in: path
      description: chat number
      required: true
      schema:
        type: string
    get:
      summary: show chat
      tags:
      - chats
      responses:
        '200':
          description: chat found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      chat:
                        type: object
                        properties:
                          token:
                            type: string
                          number:
                            type: integer
                          messages_number:
                            type: integer
                          created_at:
                            type: string
                          updated_at:
                            type: string
                required:
                - status
                - message
  "/v1/applications/{application_token}/chats/{chat_number}/messages":
    parameters:
    - name: application_token
      in: path
      description: application token
      required: true
      schema:
        type: string
    - name: chat_number
      in: path
      description: chat number
      required: true
      schema:
        type: string
    post:
      summary: create message
      tags:
      - messages
      parameters: []
      responses:
        '201':
          description: message created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      message:
                        type: object
                        properties:
                          id:
                            type: integer
                          token:
                            type: string
                          chat_number:
                            type: integer
                          number:
                            type: integer
                          messages_number:
                            type: integer
                          body:
                            type: string
                          created_at:
                            type: string
                          updated_at:
                            type: string
                required:
                - status
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
              required:
              - body
    get:
      summary: list messages
      tags:
      - messages
      responses:
        '200':
          description: Appliction found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      messages:
                        type: array
                        items:
                          type: object
                          properties:
                            token:
                              type: string
                            chat_number:
                              type: integer
                            number:
                              type: integer
                            messages_number:
                              type: integer
                            body:
                              type: string
                            created_at:
                              type: string
                            updated_at:
                              type: string
                required:
                - status
                - message
  "/v1/applications/{application_token}/chats/{chat_number}/messages/{number}":
    parameters:
    - name: application_token
      in: path
      description: application token
      required: true
      schema:
        type: string
    - name: chat_number
      in: path
      description: chat number
      required: true
      schema:
        type: string
    - name: number
      in: path
      description: message number
      required: true
      schema:
        type: string
    get:
      summary: show message
      tags:
      - messages
      responses:
        '200':
          description: message found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      message:
                        type: object
                        properties:
                          token:
                            type: string
                          chat_number:
                            type: integer
                          number:
                            type: integer
                          messages_number:
                            type: integer
                          body:
                            type: string
                          created_at:
                            type: string
                          updated_at:
                            type: string
                required:
                - status
                - message
    put:
      summary: update message
      tags:
      - messages
      parameters: []
      responses:
        '200':
          description: message updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      message:
                        type: object
                        properties:
                          token:
                            type: string
                          chat_number:
                            type: integer
                          number:
                            type: integer
                          messages_number:
                            type: integer
                          body:
                            type: string
                          created_at:
                            type: string
                          updated_at:
                            type: string
                required:
                - status
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
              required:
              - body
  "/v1/applications/{application_token}/chats/{chat_number}/search/{phrase}":
    parameters:
    - name: application_token
      in: path
      description: application_ token
      required: true
      schema:
        type: string
    - name: chat_number
      in: path
      description: chat number
      required: true
      schema:
        type: string
    - name: phrase
      in: path
      description: search phrase
      required: true
      schema:
        type: string
    get:
      summary: search message
      tags:
      - messages
      responses:
        '200':
          description: messages found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      messages:
                        type: array
                        items:
                          type: object
                          properties:
                            token:
                              type: string
                            chat_number:
                              type: integer
                            number:
                              type: integer
                            messages_number:
                              type: integer
                            body:
                              type: string
                            created_at:
                              type: string
                            updated_at:
                              type: string
                required:
                - status
                - message
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
